spring:
  datasource:
    username: 
    password: 
    url: jdbc:postgresql://localhost:5432/medical_appointment

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dilect: org.hibernate.dialect.PostgreSQLDialect
        format-sql: true

server:
  port: 5000